### ISSUE TITLE
结界挂卡没有翻找列表

### ISSUE THREAD

**Issue by LDYll1l** [runhey/OnmyojiAutoScript#141]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 最新版

### 描述你的问题

使用结界挂卡功能，设置了 太鼓4 > 太鼓5规则，想要先吃掉4星和5星太鼓留着6星，然后脚本会反复切换太鼓列表，没有往下滑动翻找，然后判定20次后程序报错结束。
规则如图，不太清楚现在是否支持结界卡翻找 还是我的规则设置有问题
![QQ图片20231204214501](https://github.com/runhey/OnmyojiAutoScript/assets/149946150/67ff1733-2e53-42ff-98eb-99772abfb04a)

### 如何复现

设置规则  太鼓4 > 太鼓5  后只要启动该功能就会出现

### 预期行为

从太鼓列表中翻找到指定规则的太鼓

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════
─────────────────────────────── KEKKAIACTIVATION ───────────────────────────────
════════════════════════════════════════════════════════════════════════════════
2023-12-04 21:05:12.527 |     INFO | Connecting to local emulator, using host 192.168.0.5                               
2023-12-04 21:05:12.542 |     INFO | Reverse server listening on 192.168.0.5:20356, client can send data to             
192.168.0.5:20356                                                                                                       
2023-12-04 21:05:12.548 |     INFO | sdk_ver: 28                                                                        
2023-12-04 21:05:12.557 |     INFO | [nc command] ['busybox', 'nc']                                                     
2023-12-04 21:05:12.685 |     INFO | [Screen_size] 1280x720                                                             
2023-12-04 21:05:12.688 |     INFO | module_path:                                                                       
D:\工具\OnmyojiAutoScript-easy-install\tasks\KekkaiActivation\script_task.py, module_name: script_task                  
2023-12-04 21:05:12.755 |     INFO | UI get current page                                                                
2023-12-04 21:05:12.792 |     INFO | Click (1171,  113) @ UI_UI_BACK_RED                                                
2023-12-04 21:05:12.919 |     INFO | Trying to switch to supported page                                                 
2023-12-04 21:05:12.923 |     INFO | Click (  46,   34) @ UI_UI_BACK_BLUE                                               
2023-12-04 21:05:13.027 |     INFO | Trying to switch to supported page                                                 
2023-12-04 21:05:13.038 |     INFO | [Package_name] com.netease.onmyoji.bili                                            
2023-12-04 21:05:13.056 |     INFO | [Device Orientation] 0 (Normal)                                                    
2023-12-04 21:05:13.197 |     INFO | Click (  61,   31) @ PAGE_SIX_GATES_GOTO_EXPLORATION                               
2023-12-04 21:05:13.307 |     INFO | Trying to switch to supported page                                                 
2023-12-04 21:05:15.228 |     INFO | [UI] page_guild                                                                    
2023-12-04 21:05:15.231 |     INFO | <<< UI GOTO PAGE_GUILD >>>                                                         
2023-12-04 21:05:15.417 |     INFO | Page arrive: page_guild                                                            
2023-12-04 21:05:15.727 |     INFO | Click (1104,  667) @ KU_GUILD_REALM                                                
2023-12-04 21:05:19.329 |     INFO | Click ( 605,  314) @ REALM_SHI_GROWN                                               
2023-12-04 21:05:20.251 |     INFO | Enter shikigami grown                                                              
2023-12-04 21:05:20.255 |     INFO | No max level shikigami                                                             
2023-12-04 21:05:20.568 |     INFO | Click (  38,   33) @ UI_UI_BACK_BLUE                                               
2023-12-04 21:05:21.758 |     INFO | Click ( 912,  316) @ REALM_SHI_CARD                                                
2023-12-04 21:05:22.661 |     INFO | Enter card page                                                                    
2023-12-04 21:05:22.663 |     INFO | <<< START ACTIVATION >>>                                                           
2023-12-04 21:05:23.284 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:23.568 |     INFO | Click ( 470,  138) @ a_select_card_list                                            
2023-12-04 21:05:24.573 |     INFO | Appear card class: taiko                                                           
2023-12-04 21:05:24.883 |     INFO | Click ( 421,  285) @ A_A_CARD_KAIKO                                                
2023-12-04 21:05:25.173 |     INFO | Selected card class: taiko                                                         
2023-12-04 21:05:25.781 |     INFO | No target card found                                                               
2023-12-04 21:05:26.091 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:26.395 |     INFO | Click ( 459,  112) @ a_select_card_list                                            
2023-12-04 21:05:27.419 |     INFO | Appear card class: taiko                                                           
2023-12-04 21:05:27.707 |     INFO | Click ( 514,  244) @ A_A_CARD_KAIKO                                                
2023-12-04 21:05:28.025 |     INFO | Selected card class: taiko                                                         
2023-12-04 21:05:28.641 |     INFO | No target card found                                                               
2023-12-04 21:05:28.927 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:29.221 |     INFO | Click ( 437,  129) @ a_select_card_list                                            
2023-12-04 21:05:29.930 |     INFO | Appear card class: taiko                                                           
2023-12-04 21:05:30.231 |     INFO | Click ( 505,  272) @ A_A_CARD_KAIKO                                                
2023-12-04 21:05:30.517 |     INFO | Selected card class: taiko                                                         
2023-12-04 21:05:31.141 |     INFO | No target card found                                                               
2023-12-04 21:05:31.437 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:31.745 |     INFO | Click ( 480,  120) @ a_select_card_list                                            
2023-12-04 21:05:32.495 |     INFO | Appear card class: taiko                                                           
2023-12-04 21:05:32.755 |     INFO | Click ( 431,  269) @ A_A_CARD_KAIKO                                                
2023-12-04 21:05:33.071 |     INFO | Selected card class: taiko                                                         
2023-12-04 21:05:33.663 |     INFO | No target card found                                                               
2023-12-04 21:05:33.967 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:34.275 |     INFO | Click ( 449,  113) @ a_select_card_list                                            
2023-12-04 21:05:35.285 |     INFO | Appear card class: taiko                                                           
2023-12-04 21:05:35.586 |     INFO | Click ( 427,  255) @ A_A_CARD_KAIKO                                                
2023-12-04 21:05:35.884 |     INFO | Selected card class: taiko                                                         
2023-12-04 21:05:36.532 |     INFO | No target card found                                                               
2023-12-04 21:05:36.807 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:37.101 |     INFO | Click ( 407,  113) @ a_select_card_list                                            
2023-12-04 21:05:38.111 |     INFO | Appear card class: taiko                                                           
2023-12-04 21:05:38.425 |     INFO | Click ( 378,  293) @ A_A_CARD_KAIKO                                                
2023-12-04 21:05:38.721 |     INFO | Selected card class: taiko                                                         
2023-12-04 21:05:39.322 |     INFO | No target card found                                                               
2023-12-04 21:05:39.653 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:39.939 |     INFO | Click ( 481,  121) @ a_select_card_list                                            
2023-12-04 21:05:40.956 |     INFO | Appear card class: taiko                                                           
2023-12-04 21:05:41.268 |     INFO | Click ( 387,  238) @ A_A_CARD_KAIKO                                                
2023-12-04 21:05:41.581 |     INFO | Selected card class: taiko                                                         
2023-12-04 21:05:42.179 |     INFO | No target card found                                                               
2023-12-04 21:05:42.479 |     INFO | Card is not selected also not using                                                
2023-12-04 21:05:42.785 |  WARNING | Too many click between 2 buttons: A_A_CARD_KAIKO, a_select_card_list               
2023-12-04 21:05:42.786 |  WARNING | History click: ['a_select_card_list', 'A_A_CARD_KAIKO', 'a_select_card_list',      
'A_A_CARD_KAIKO', 'a_select_card_list', 'A_A_CARD_KAIKO', 'a_select_card_list', 'A_A_CARD_KAIKO', 'a_select_card_list', 
'A_A_CARD_KAIKO', 'a_select_card_list', 'A_A_CARD_KAIKO', 'a_select_card_list', 'A_A_CARD_KAIKO', 'a_select_card_list'] 
2023-12-04 21:05:42.788 |    ERROR | GameTooManyClickError: Too many click between 2 buttons: A_A_CARD_KAIKO,           
a_select_card_list                                                                                                      
2023-12-04 21:05:42.790 |  WARNING | Saving error: ./log/error/1701695142790
```

### 截图

![2023-12-04_21-05-42-784594](https://github.com/runhey/OnmyojiAutoScript/assets/149946150/aaead84a-d886-4b8c-a766-97ac7aff21e9)

**Comment by runhey** [comment]
没有发现任何卡，跑循环去了，你应该把太鼓六星加上

**Comment by LDYll1l** [comment]
> 不过你要是太鼓六星太多的话可能会到滑动太多次
 
如果我设置成  太鼓4 > 太鼓5  > 太鼓6 ，就会直接选择6星太鼓，没有进行滑动，我是想要先吃掉4星和5星太鼓留着6星。
我的问题应该是出在没有滑动查找。

**Comment by runhey** [comment]
你要明白，要先把日志扔出来，就好比事实基于数据，谁知道你说的是什么

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/116537a3-c80f-4f73-90dc-84adaf4a9898)

**Comment by runhey** [comment]
‘’‘
INFO     2023-12-05 13:54:36.503 │ [UI] page_guild                             
INFO     2023-12-05 13:54:36.503 │ <<< UI GOTO PAGE_GUILD >>>                  
INFO     2023-12-05 13:54:36.892 │ Page arrive: page_guild                     
INFO     2023-12-05 13:54:37.282 │ Click (1079,  645) @ KU_GUILD_REALM         
INFO     2023-12-05 13:54:40.244 │ Click ( 608,  326) @ REALM_SHI_GROWN        
INFO     2023-12-05 13:54:41.006 │ Enter shikigami grown                       
INFO     2023-12-05 13:54:41.009 │ No max level shikigami                      
INFO     2023-12-05 13:54:41.655 │ Click (  24,   27) @ UI_UI_BACK_BLUE        
INFO     2023-12-05 13:54:43.236 │ Click ( 893,  339) @ REALM_SHI_CARD         
INFO     2023-12-05 13:54:43.863 │ Enter card page                             
INFO     2023-12-05 13:54:43.866 │ <<< START ACTIVATION >>>                    
INFO     2023-12-05 13:54:44.602 │ Card is not selected also not using         
INFO     2023-12-05 13:54:44.902 │ Click ( 393,  129) @ a_select_card_list     
INFO     2023-12-05 13:54:45.744 │ Appear card class: taiko                    
INFO     2023-12-05 13:54:46.032 │ Click ( 426,  253) @ A_A_CARD_KAIKO         
INFO     2023-12-05 13:54:46.326 │ Selected card class: taiko                  
INFO     2023-12-05 13:54:46.942 │ Current best card class: taiko_6            
INFO     2023-12-05 13:54:46.943 │ Current select card: CardClass.TAIKO6       
INFO     2023-12-05 13:54:47.526 │ Click ( 192,  537) @ CARDS_CARDS_KAIKO_6    
INFO     2023-12-05 13:54:47.840 │ Swipe ( 198,  423) -> ( 179,  190)          
INFO     2023-12-05 13:54:50.670 │ Current best card class: taiko_6            
INFO     2023-12-05 13:54:50.671 │ Current select card: CardClass.TAIKO6       
INFO     2023-12-05 13:54:50.953 │ Click ( 215,  558) @ CARDS_CARDS_KAIKO_6    
INFO     2023-12-05 13:54:51.004 │ Swipe ( 181,  409) -> ( 200,  169)          
INFO     2023-12-05 13:54:53.827 │ Current best card class: taiko_6            
INFO     2023-12-05 13:54:53.828 │ Current select card: CardClass.TAIKO6       
INFO     2023-12-05 13:54:54.123 │ Click ( 222,  257) @ CARDS_CARDS_KAIKO_6    
INFO     2023-12-05 13:54:54.174 │ Swipe ( 198,  402) -> ( 181,  191)          
INFO     2023-12-05 13:54:57.000 │ Current best card class: taiko_6            
INFO     2023-12-05 13:54:57.001 │ Current select card: CardClass.TAIKO6       
INFO     2023-12-05 13:54:57.303 │ Click ( 234,  459) @ CARDS_CARDS_KAIKO_6    
INFO     2023-12-05 13:54:57.356 │ Swipe ( 179,  405) -> ( 179,  184)          
INFO     2023-12-05 13:54:57.357 │ Swipe x distance is 0                       
INFO     2023-12-05 13:55:00.158 │ Current best card class: taiko_5            
INFO     2023-12-05 13:55:00.159 │ Current select card: CardClass.TAIKO5       
INFO     2023-12-05 13:55:00.449 │ Click ( 242,  405) @ CARDS_CARDS_KAIKO_5    
INFO     2023-12-05 13:55:00.747 │ Card is selected but not using              
INFO     2023-12-05 13:55:01.055 │ Click (1065,  570) @ A_A_ACTIVATE_YELLOW    
INFO     2023-12-05 13:55:01.627 │ Click ( 783,  448) @ UI_UI_CONFIRM          
INFO     2023-12-05 13:55:02.276 │ Card is activated                           
INFO     2023-12-05 13:55:02.717 │ [CARD_ALL_TIME 0.152s] [23:5959]            
INFO     2023-12-05 13:55:02.718 │ Delay task `kekkai_activation` to 2023-12-05
         23:55:02 (success=True, server_update=True,                           
         target=datetime.datetime(2023, 12, 6, 13, 55, 1, 718419))             
INFO     2023-12-05 13:55:02.720 │ [kekkai_activation.scheduler.next_run]      
         2023-12-05 23:55:02                                                   
write: D:\Project\OnmyojiAutoScript\config\oas1.json
INFO     2023-12-05 13:55:02.958 │ Click (1182,   96) @ UI_UI_BACK_RED         
INFO     2023-12-05 13:55:04.067 │ Click ( 606,  323) @ REALM_SHI_GROWN        
INFO     2023-12-05 13:55:04.807 │ Enter shikigami grown                       
INFO     2023-12-05 13:55:04.810 │ No max level shikigami                      
INFO     2023-12-05 13:55:05.453 │ Click (  44,   27) @ UI_UI_BACK_BLUE        
INFO     2023-12-05 13:55:06.903 │ Click (  47,   36) @ UI_UI_BACK_BLUE        
Traceback (most recent call last):
  File "D:\Project\OnmyojiAutoScript\tasks\KekkaiActivation\script_task.py", line 382, in <module>
    t.run()
  File "D:\Project\OnmyojiAutoScript\tasks\KekkaiActivation\script_task.py", line 51, in run
    raise TaskEnd('KekkaiActivation')
module.exception.TaskEnd: KekkaiActivation
’‘’

**Comment by runhey** [comment]
我自己跑的没有问题

**Comment by runhey** [comment]
```
       # 得了开始一直往下滑动 找最优卡
        card_best = None
        swipe_count = 0
        while 1:
            self.screenshot()
            current_best = self._current_select_best(card_best)
            if current_best is None:
                break

            if current_best == self.order_cards[0]:
                break
            # 为什么找到第二个最优解也是会退出呢？？？
            # 这个是因为一般是从高星到低星来找， 基本上第二个最优解就是最优解了
            elif current_best == self.order_cards[1]:
                break

            # 超过十次就退出
            if swipe_count > 20:
                logger.warning('Swipe count is more than 10')
                break
            # 一直向下滑动
            self.swipe(self.S_CARDS_SWIPE, interval=0.9)
            swipe_count += 1
```
源码

**Comment by LDYll1l** [comment]
> 不过你要是太鼓六星太多的话可能会到滑动太多次

不好意思了前面太鼓4>太鼓5>太鼓6那个描述有问题，确实是因为太鼓6太多了没有滑动到xi下面的四星和五星。
![QQ图片20231205193654](https://github.com/runhey/OnmyojiAutoScript/assets/149946150/4b33a5cc-ecab-49b4-9d9f-567f011848ef)
![QQ图片20231205193702](https://github.com/runhey/OnmyojiAutoScript/assets/149946150/f01993a4-978c-426c-8b76-09e345e85654)
