### ISSUE TITLE
点击Task List出现网络错误

### ISSUE THREAD

**Issue by jiaysr** [runhey/OnmyojiAutoScript#331]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

oasx点击任意task都会出现网络错误

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\toolkit\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\module\server\script_router.py", line 65, in script_task
    return mm.config_cache(script_name).model.script_task(task)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\module\server\main_manager.py", line 100, in config_cache
    return Config(name)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\module\config\config.py", line 107, in __init__
    self.model = ConfigModel(config_name=config_name)
  File "D:\yysoas\oas\OnmyojiAutoScript-easy-install\module\config\config_model.py", line 143, in __init__
    super().__init__(**data)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConfigModel
realm_raid -> raid_config -> number_base
  ensure this value is less than or equal to 20 (type=value_error.number.not_le; limit_value=20)
```

### 截图

![QQ20240717-114412](https://github.com/user-attachments/assets/02b50967-6868-4a90-844e-cd3457dffbc5)

**Comment by runhey** [comment]
pydantic.error_wrappers.ValidationError: 1 validation error for ConfigModel
realm_raid -> raid_config -> number_base
  ensure this value is less than or equal to 20 (type=value_error.number.not_le; limit_value=20)
配置文件出错，两种方式
### 1
在./config/文件夹下找到对应的配置，然后修改，重启
### 2
删掉这个配置新建一个



你，不要随便动这个值`个人突破->突破卷数量大于等于 X 时才会挑战`
